version: '3.7'
services:
  gitlab-runner1:
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    volumes:
      - './gitlab-runner1-config:/etc/gitlab-runner:Z'
      - '/var/run/docker.sock:/var/run/docker.sock'

networks:
  default:
    name: gitlab
